#part1 - vote/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-voting-app-vote
  namespace: voting-app
  #use namespace voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-voting-app-vote
  template:
    metadata:
      labels:
        app: my-voting-app-vote
    spec:
      containers:
        - name: my-voting-app-vote
          image: dockersamples/examplevotingapp_vote:latest
          ports:
          - containerPort: 80
          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef:
                  name: config-vote
                  key: OPTION_A
            - name: OPTION_B
              valueFrom:
                configMapKeyRef:
                  name: config-vote
                  key: OPTION_B
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-vote
                  key: REDIS_HOST
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
