apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-voting-app-worker
  namespace: voting-app
  #use namespace voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-voting-app-worker
  template:
    metadata:
      labels:
        app: my-voting-app-worker
    spec:
      containers:
      - name: my-voting-app-worker
        image: dockersamples/examplevotingapp_worker:latest
        env:
        #configure environment variables for redis and postgres connections
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: config-worker
              key: REDIS_HOST
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: config-worker
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          value: "votingdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
            
