apiVersion: v1
kind: ConfigMap
metadata:
  name: config-vote
  namespace: voting-app
data:
  OPTION_A: "cats"
  OPTION_B: "dogs"
  REDIS_HOST: "my-voting-app-redis.voting-app.svc.cluster.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-worker
  namespace: voting-app
data:
  REDIS_HOST: my-voting-app-redis.voting-app.svc.cluster.local
  POSTGRES_HOST: my-voting-app-db.voting-app.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-results
  namespace: voting-app
data:
  POSTGRES_HOST: my-voting-app-db.voting-app.svc.cluster.local
